version: 1.2
class: CommandLineTool
workflows:
   - name: GRAPE preprocessing
     subclass: CWL
     publish: true
     primaryDescriptorPath: workflows/preprocess2/cwl/preprocess.cwl
     testParameterFiles:
      - workflows/preprocess2/cwl/config.json

   - name: GRAPE reference downloading
     subclass: CWL
     publish: true
     primaryDescriptorPath: workflows/reference/cwl/ref.cwl
     testParameterFiles:
       - workflows/reference/cwl/config.json

   - name: GRAPE reference minimal downloading
     subclass: CWL
     publish: true
     primaryDescriptorPath: workflows/reference/cwl/ref_min.cwl
     testParameterFiles:
       - workflows/reference/cwl/config.json

   - name: GRAPE bundle downloading
     subclass: CWL
     publish: true
     primaryDescriptor: workflows/bundle/cwl/bundle.cwl
     testParameterFiles:
       - workflows/bundle/cwl/config.json

   - name: GRAPE bundle minimal downloading
     subclass: CWL
     publish: true
     primaryDescriptor: workflows/bundle/cwl/bundle_min.cwl
     testParameterFiles:
       - workflows/bundle/cwl/config.json

   - name: GRAPE simulation
     subclass: CWL
     publish: true
     primaryDescriptorPath: workflows/pedsim/cwl/simulation.cwl
     testParameterFiles:
       - workflows/pedsim/cwl/config.json
