name: Run Python Tests

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    # Self-hosted runner
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt
      - run: |
          pytest test/test.py
