name: verify-files

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  verify-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        run: "python -m pip install pyyaml"

      - name: Validate
        run: "python validate_files.py config.yaml"
